name: Publish
on: [workflow_dispatch] # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - run: apt update && apt install git -y && git --version
      - run: git config --global --add safe.directory /__w/Blockus/Blockus
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FabricMC/fabric-action-scripts@v2
        id: changelog
        with:
          context: changelog
          workflow_id: publish.yml
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publish --stacktrace -Porg.gradle.parallel.threads=4
      - name: Upload GitHub release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'build/libs/*.jar;!build/libs/*-sources.jar;!build/libs/*-dev.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
